spring:
  application:
    name: membership-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
