spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

# kafka
kafka:
  bootstrap:
    addresses: ${spring.embedded.kafka.brokers:localhost:9092}
